// Computer History foundation rules; DSH tokens remain the color source.
export const FOUNDATION_STYLES = `
.ch-main{box-sizing:border-box;width:min(940px,100%);max-width:940px;margin:0 auto;padding:28px 32px 42px;color:var(--dsw-alias-label-primary)}
.ch-main-header{margin-bottom:20px}
.ch-heading{min-width:0}.ch-heading h1{margin:0 0 6px;font-size:28px;line-height:1.2;letter-spacing:-.02em}.ch-subtitle{margin:0;max-width:620px;color:var(--dsw-alias-label-secondary);font-size:14px;line-height:1.55}
.ch-status-line{display:flex;align-items:center;gap:7px;min-width:0;margin-top:11px;color:var(--dsw-alias-label-secondary);font-size:12px;line-height:1.45;white-space:nowrap}
.ch-status-dot{flex:0 0 auto;width:7px;height:7px;border-radius:999px;background:var(--dsw-alias-state-idle-primary)}.ch-status-dot-success{background:var(--dsw-alias-state-success-primary)}.ch-status-dot-warn{background:var(--dsw-alias-state-warn-primary)}.ch-status-dot-error{background:var(--dsw-alias-state-error-primary)}
.ch-status-primary{color:var(--dsw-alias-label-primary);font-weight:600}.ch-status-meta,.ch-status-summary{overflow:hidden;text-overflow:ellipsis}.ch-status-separator{opacity:.65}
.ch-muted{color:var(--dsw-alias-label-secondary);line-height:1.55}.ch-alert{margin:0 0 18px;padding:11px 13px;border:1px solid var(--dsw-alias-border-l1);border-left:3px solid var(--dsw-alias-brand-primary);border-radius:10px;background:var(--dsw-alias-bg-layer-1)}
.ch-alert p{margin:0}.ch-alert p+p{margin-top:6px}.ch-section{margin:0 0 22px}.ch-section-title{margin:0 0 9px;font-size:17px;line-height:1.4}
.ch-button{appearance:none;height:34px;padding:0 13px;border:0;border-radius:10px;background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary);font:inherit;font-size:13px;font-weight:550;cursor:pointer}
.ch-button:hover:not(:disabled){box-shadow:inset 0 0 0 1px var(--dsw-alias-border-l2)}.ch-button:disabled{opacity:.5;cursor:default}.ch-button-danger{color:var(--dsw-alias-state-error-primary);background:transparent;box-shadow:inset 0 0 0 1px var(--dsw-alias-border-l1)}
.ch-button:focus-visible,.ch-text-action:focus-visible,.ch-input:focus-visible,.ch-switch:focus-visible,.ch-timeline-action:focus-visible,.ch-thread-action:focus-visible,.ch-inspector>summary:focus-visible,.ch-resume-search>summary:focus-visible,.ch-summary-disclosure>summary:focus-visible{outline:2px solid var(--dsw-alias-brand-primary);outline-offset:2px}
.ch-settings-summary:focus-visible,.ch-day-summary:focus-visible,.ch-project-day-head:focus-visible{outline:none;box-shadow:inset 0 0 0 2px var(--dsw-alias-brand-primary);border-radius:8px}
.ch-code{display:block;box-sizing:border-box;max-width:100%;margin:8px 0 0;padding:10px 12px;border-radius:10px;background:var(--dsw-alias-bg-layer-2);overflow-x:auto;font-size:12px}
.ch-feedback{margin:8px 0 0;font-size:12px;line-height:1.5;color:var(--dsw-alias-state-success-primary)}.ch-feedback-error{color:var(--dsw-alias-state-error-primary)}
.ch-inline-failure{display:flex;align-items:center;gap:10px}.ch-inline-failure .ch-muted{margin:0}.ch-text-action{appearance:none;padding:2px 0;border:0;background:transparent;color:var(--dsw-alias-brand-primary);font:inherit;font-size:12px;font-weight:600;cursor:pointer}.ch-text-action:hover{text-decoration:underline}
.ch-visually-hidden{position:absolute!important;width:1px!important;height:1px!important;padding:0!important;margin:-1px!important;overflow:hidden!important;clip:rect(0,0,0,0)!important;white-space:nowrap!important;border:0!important}.ch-state-card{display:grid;grid-template-columns:40px minmax(0,1fr) auto;align-items:center;gap:14px;max-width:720px;padding:18px 20px;border:1px solid var(--dsw-alias-border-l1);border-radius:14px;background:var(--dsw-alias-bg-base)}.ch-state-mark{display:grid;place-items:center;width:38px;height:38px;border-radius:12px;background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-state-error-primary);font-size:16px;font-weight:700}.ch-state-copy h2{margin:0;font-size:15px}.ch-state-copy p{margin:4px 0 0;font-size:12px}
.ch-skeleton-surface{overflow:hidden;border:1px solid var(--dsw-alias-border-l1);border-radius:14px;background:var(--dsw-alias-bg-base)}.ch-skeleton-head{display:flex;align-items:center;justify-content:space-between;padding:14px 16px}.ch-skeleton-row{display:grid;grid-template-columns:92px minmax(0,1fr) 48px;align-items:center;gap:14px;min-height:54px;margin:0 16px;border-top:1px solid var(--dsw-alias-border-l1)}.ch-skeleton-line{display:block;height:9px;border-radius:999px;background:var(--dsw-alias-border-l2)}.ch-skeleton-copy{display:grid;gap:6px}.ch-skeleton-long{width:min(240px,78%)}.ch-skeleton-medium{width:min(170px,62%)}.ch-skeleton-short{width:88px}.ch-skeleton-small{width:72px;height:7px}.ch-skeleton-tiny{width:48px;height:7px}.ch-skeleton-time{width:70px;height:7px}.ch-skeleton-thread{display:grid;grid-template-columns:minmax(0,1fr) 70px;align-items:center;gap:10px;padding:12px 14px;border:1px solid var(--dsw-alias-border-l1);border-radius:14px;background:var(--dsw-alias-bg-base)}
.ch-first-run{box-sizing:border-box;max-width:680px;margin:36px 0 0;padding:26px 28px;border:1px solid var(--dsw-alias-border-l1);border-radius:15px;background:var(--dsw-alias-bg-base)}.ch-first-run-mark{display:grid;place-items:center;width:38px;height:38px;margin-bottom:18px;border-radius:12px;background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-brand-primary);font-size:18px;font-weight:700}.ch-first-run h2{margin:0;font-size:20px;line-height:1.35}.ch-first-run-lead{max-width:580px;margin:8px 0 0;color:var(--dsw-alias-label-secondary);font-size:13px;line-height:1.6}.ch-first-run-points{display:grid;gap:8px;margin:20px 0 0;padding:14px 0;border-top:1px solid var(--dsw-alias-border-l1);border-bottom:1px solid var(--dsw-alias-border-l1);color:var(--dsw-alias-label-secondary);font-size:12px;line-height:1.55}.ch-first-run-action{display:flex;align-items:center;gap:12px;margin-top:16px}.ch-first-run-action .ch-button{box-shadow:inset 0 0 0 1px var(--dsw-alias-brand-primary);color:var(--dsw-alias-brand-primary)}.ch-first-run-action .ch-muted{margin:0;font-size:11px}
`
