const CSS = `
.ch-main{box-sizing:border-box;width:min(940px,100%);max-width:940px;margin:0 auto;padding:28px 32px 42px;color:var(--dsw-alias-label-primary)}
.ch-main-header{margin-bottom:20px}
.ch-heading{min-width:0}.ch-heading h1{margin:0 0 6px;font-size:28px;line-height:1.2;letter-spacing:-.02em}.ch-subtitle{margin:0;max-width:620px;color:var(--dsw-alias-label-secondary);font-size:14px;line-height:1.55}
.ch-status-line{display:flex;align-items:center;gap:7px;min-width:0;margin-top:11px;color:var(--dsw-alias-label-secondary);font-size:12px;line-height:1.45;white-space:nowrap}
.ch-status-dot{flex:0 0 auto;width:7px;height:7px;border-radius:999px;background:var(--dsw-alias-state-idle-primary)}.ch-status-dot-success{background:var(--dsw-alias-state-success-primary)}.ch-status-dot-warn{background:var(--dsw-alias-state-warn-primary)}.ch-status-dot-error{background:var(--dsw-alias-state-error-primary)}
.ch-status-primary{color:var(--dsw-alias-label-primary);font-weight:600}.ch-status-meta,.ch-status-summary{overflow:hidden;text-overflow:ellipsis}.ch-status-separator{opacity:.65}
.ch-muted{color:var(--dsw-alias-label-secondary);line-height:1.55}.ch-alert{margin:0 0 18px;padding:11px 13px;border:1px solid var(--dsw-alias-border-l1);border-left:3px solid var(--dsw-alias-brand-primary);border-radius:10px;background:var(--dsw-alias-bg-layer-1)}
.ch-alert p{margin:0}.ch-alert p+p{margin-top:6px}.ch-section{margin:0 0 22px}.ch-section-title{margin:0 0 9px;font-size:17px;line-height:1.4}
.ch-button{appearance:none;height:34px;padding:0 13px;border:0;border-radius:10px;background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary);font:inherit;font-size:13px;font-weight:550;cursor:pointer}
.ch-button:hover:not(:disabled){box-shadow:inset 0 0 0 1px var(--dsw-alias-border-l2)}.ch-button:disabled{opacity:.5;cursor:default}.ch-button-danger{color:var(--dsw-alias-state-error-primary);background:transparent;box-shadow:inset 0 0 0 1px var(--dsw-alias-border-l1)}
.ch-button:focus-visible,.ch-text-action:focus-visible,.ch-input:focus-visible,.ch-switch:focus-visible,.ch-timeline-action:focus-visible,.ch-thread-action:focus-visible,.ch-inspector>summary:focus-visible,.ch-resume-search>summary:focus-visible,.ch-summary-disclosure>summary:focus-visible{outline:2px solid var(--dsw-alias-brand-primary);outline-offset:2px}
.ch-settings-summary:focus-visible,.ch-day-summary:focus-visible,.ch-project-day-head:focus-visible{outline:none;box-shadow:inset 0 0 0 2px var(--dsw-alias-brand-primary);border-radius:8px}
.ch-code{display:block;box-sizing:border-box;max-width:100%;margin:8px 0 0;padding:10px 12px;border-radius:10px;background:var(--dsw-alias-bg-layer-2);overflow-x:auto;font-size:12px}
.ch-feedback{margin:8px 0 0;font-size:12px;line-height:1.5;color:var(--dsw-alias-state-success-primary)}.ch-feedback-error{color:var(--dsw-alias-state-error-primary)}
.ch-inline-failure{display:flex;align-items:center;gap:10px}.ch-inline-failure .ch-muted{margin:0}.ch-text-action{appearance:none;padding:2px 0;border:0;background:transparent;color:var(--dsw-alias-brand-primary);font:inherit;font-size:12px;font-weight:600;cursor:pointer}.ch-text-action:hover{text-decoration:underline}
.ch-visually-hidden{position:absolute!important;width:1px!important;height:1px!important;padding:0!important;margin:-1px!important;overflow:hidden!important;clip:rect(0,0,0,0)!important;white-space:nowrap!important;border:0!important}.ch-state-card{display:grid;grid-template-columns:40px minmax(0,1fr) auto;align-items:center;gap:14px;max-width:720px;padding:18px 20px;border:1px solid var(--dsw-alias-border-l1);border-radius:14px;background:var(--dsw-alias-bg-base)}.ch-state-mark{display:grid;place-items:center;width:38px;height:38px;border-radius:12px;background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-state-error-primary);font-size:16px;font-weight:700}.ch-state-copy h2{margin:0;font-size:15px}.ch-state-copy p{margin:4px 0 0;font-size:12px}
.ch-skeleton-surface{overflow:hidden;border:1px solid var(--dsw-alias-border-l1);border-radius:14px;background:var(--dsw-alias-bg-base)}.ch-skeleton-head{display:flex;align-items:center;justify-content:space-between;padding:14px 16px}.ch-skeleton-row{display:grid;grid-template-columns:92px minmax(0,1fr) 48px;align-items:center;gap:14px;min-height:54px;margin:0 16px;border-top:1px solid var(--dsw-alias-border-l1)}.ch-skeleton-line{display:block;height:9px;border-radius:999px;background:var(--dsw-alias-border-l2)}.ch-skeleton-copy{display:grid;gap:6px}.ch-skeleton-long{width:min(240px,78%)}.ch-skeleton-medium{width:min(170px,62%)}.ch-skeleton-short{width:88px}.ch-skeleton-small{width:72px;height:7px}.ch-skeleton-tiny{width:48px;height:7px}.ch-skeleton-time{width:70px;height:7px}.ch-skeleton-thread{display:grid;grid-template-columns:minmax(0,1fr) 70px;align-items:center;gap:10px;padding:12px 14px;border:1px solid var(--dsw-alias-border-l1);border-radius:14px;background:var(--dsw-alias-bg-base)}
.ch-first-run{box-sizing:border-box;max-width:680px;margin:36px 0 0;padding:26px 28px;border:1px solid var(--dsw-alias-border-l1);border-radius:15px;background:var(--dsw-alias-bg-base)}.ch-first-run-mark{display:grid;place-items:center;width:38px;height:38px;margin-bottom:18px;border-radius:12px;background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-brand-primary);font-size:18px;font-weight:700}.ch-first-run h2{margin:0;font-size:20px;line-height:1.35}.ch-first-run-lead{max-width:580px;margin:8px 0 0;color:var(--dsw-alias-label-secondary);font-size:13px;line-height:1.6}.ch-first-run-points{display:grid;gap:8px;margin:20px 0 0;padding:14px 0;border-top:1px solid var(--dsw-alias-border-l1);border-bottom:1px solid var(--dsw-alias-border-l1);color:var(--dsw-alias-label-secondary);font-size:12px;line-height:1.55}.ch-first-run-action{display:flex;align-items:center;gap:12px;margin-top:16px}.ch-first-run-action .ch-button{box-shadow:inset 0 0 0 1px var(--dsw-alias-brand-primary);color:var(--dsw-alias-brand-primary)}.ch-first-run-action .ch-muted{margin:0;font-size:11px}

/* Timeline is the product surface: one restrained container, date groups, readable rows. */
.ch-timeline-shell{overflow:hidden;border:1px solid var(--dsw-alias-border-l1);border-radius:14px;background:var(--dsw-alias-bg-base)}
.ch-day{border-top:1px solid var(--dsw-alias-border-l1)}.ch-day:first-child{border-top:0}.ch-day-summary{display:flex;align-items:baseline;gap:10px;padding:14px 18px;cursor:pointer;list-style:none}.ch-day-summary::-webkit-details-marker{display:none}.ch-day-title{font-size:15px;font-weight:650}.ch-day-date{color:var(--dsw-alias-label-secondary);font-size:12px}.ch-day-total{margin-left:auto;color:var(--dsw-alias-label-secondary);font-size:12px;font-weight:550}.ch-day-chevron{margin-left:-2px;color:var(--dsw-alias-label-secondary);font-size:14px;line-height:1;transition:transform .16s ease}.ch-day[open] .ch-day-chevron{transform:rotate(180deg)}
.ch-timeline-list{list-style:none;margin:0;padding:0 18px 6px}.ch-timeline-item{position:relative;display:grid;grid-template-columns:88px minmax(0,1fr) auto;align-items:center;gap:14px;min-height:66px;border-top:1px solid var(--dsw-alias-border-l1)}.ch-timeline-item::after{content:"";position:absolute;z-index:0;left:120px;top:0;bottom:0;width:1px;background:var(--dsw-alias-border-l1);pointer-events:none}.ch-timeline-item:first-child::after{top:33px}.ch-timeline-item:last-child::after{bottom:33px}
.ch-time{font-size:12px;color:var(--dsw-alias-label-secondary);font-variant-numeric:tabular-nums}.ch-timeline-action{position:relative;z-index:1;appearance:none;display:grid;grid-template-columns:38px minmax(0,1fr);align-items:center;gap:11px;min-width:0;padding:10px 0;border:0;background:transparent;color:var(--dsw-alias-label-primary);font:inherit;text-align:left;cursor:pointer}.ch-timeline-action:hover .ch-episode-title{text-decoration:underline;text-decoration-color:var(--dsw-alias-brand-primary)}.ch-timeline-action-selected .ch-app-mark{box-shadow:inset 0 0 0 1px var(--dsw-alias-brand-primary)}.ch-timeline-action-selected .ch-episode-title{color:var(--dsw-alias-brand-primary)}
.ch-app-mark{position:relative;z-index:1;display:grid;place-items:center;box-sizing:border-box;width:36px;height:36px;flex:0 0 36px;border:1px solid var(--dsw-alias-border-l1);border-radius:10px;background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary);font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px;font-weight:750;letter-spacing:-.02em}
.ch-app-icon{overflow:hidden;font-family:inherit;font-size:11px;letter-spacing:0}.ch-app-icon>svg{display:block;width:23px;height:23px}.ch-app-icon-compact{width:28px;height:28px;flex-basis:28px;border-radius:8px}.ch-app-icon-compact>svg{width:18px;height:18px}.ch-app-icon-compact.ch-app-icon-chrome::before{inset:6px}.ch-app-icon-compact .ch-app-icon-core{width:11px;height:11px}.ch-app-icon-terminal{background:#181a1f;color:#f4f6f8;border-color:rgba(255,255,255,.10)}.ch-app-icon-vscode{background:#1479c9;color:#fff;border-color:transparent}.ch-app-icon-xcode{background:linear-gradient(145deg,#66bfff,#177dcc);color:#fff;border-color:transparent}.ch-app-icon-files{background:linear-gradient(90deg,#55b7f5 0 50%,#eef8ff 50%);color:#174663;border-color:rgba(20,91,133,.18)}.ch-app-icon-preview{background:linear-gradient(145deg,#4b9fe9,#286db8);color:#fff;border-color:transparent}.ch-app-icon-notes{background:#f8f8f4;color:#6d634e;border-color:#e8dfc8}.ch-app-icon-safari{background:linear-gradient(145deg,#55c7ff,#087dde);color:#fff;border-color:transparent}.ch-app-icon-chrome{position:relative;background:conic-gradient(#e94235 0 33.33%,#f6c443 33.33% 66.66%,#38a85a 66.66% 100%);border-color:rgba(0,0,0,.08)}.ch-app-icon-chrome::before{content:"";position:absolute;inset:8px;border-radius:999px;background:#fff}.ch-app-icon-core{position:relative;z-index:1;width:14px;height:14px;border-radius:999px;background:#4285f4;box-shadow:inset 0 0 0 1px rgba(0,0,0,.08)}.ch-app-icon-edge{background:linear-gradient(145deg,#12b8a6,#1278d5);color:#fff;border-color:transparent}.ch-app-icon-chatgpt{background:#176b5b;color:#fff;border-color:transparent}.ch-app-icon-generic{background:var(--dsw-alias-bg-layer-2);font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-weight:750;letter-spacing:-.02em}.ch-episode-copy{min-width:0}.ch-episode-title{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:14px;font-weight:650}.ch-episode-meta{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;margin-top:3px;color:var(--dsw-alias-label-secondary);font-size:12px}.ch-duration-wrap{display:grid;justify-items:end;gap:5px;min-width:66px}.ch-duration{font-size:12px;font-weight:550;color:var(--dsw-alias-label-secondary);font-variant-numeric:tabular-nums}.ch-duration-track{display:block;width:54px;height:2px;overflow:hidden;border-radius:999px;background:var(--dsw-alias-border-l1)}.ch-duration-fill{display:block;height:100%;border-radius:inherit;background:var(--dsw-alias-label-secondary);opacity:.48}
.ch-app-mark-image{position:absolute;z-index:3;inset:1px;width:calc(100% - 2px);height:calc(100% - 2px);object-fit:contain;border-radius:9px;background:var(--dsw-alias-bg-base)}.ch-app-mark-image[hidden]{display:none}.ch-app-icon-compact .ch-app-mark-image{border-radius:7px}
.ch-timeline-more{display:flex;justify-content:center;margin-top:9px}.ch-timeline-more .ch-text-action:disabled{opacity:.55;cursor:default}.ch-detail{margin:10px 16px 14px;padding:12px 14px;border:1px solid var(--dsw-alias-border-l1);border-radius:10px;background:var(--dsw-alias-bg-layer-1)}.ch-timeline-detail{position:relative;z-index:1;grid-column:2/-1;margin:-2px 0 11px;padding:0 0 10px 49px;border:0;border-radius:0;background:transparent}.ch-timeline-detail>.ch-detail-resource{margin:0}.ch-timeline-detail>.ch-inspector{margin-top:7px;padding-top:7px}.ch-detail-head{display:flex;align-items:center;gap:11px}.ch-detail-copy{min-width:0;flex:1}.ch-detail-title{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:13px;font-weight:650}.ch-detail-meta{display:block;margin-top:2px;color:var(--dsw-alias-label-secondary);font-size:11px}.ch-detail-resource{margin:9px 0 0;color:var(--dsw-alias-label-secondary);font-size:12px;line-height:1.5}.ch-segment-list{list-style:none;margin:7px 0 0;padding:0;display:grid;gap:5px}.ch-segment-list>li{display:grid;grid-template-columns:92px minmax(0,1fr);gap:10px;font-size:11px;line-height:1.45}.ch-segment-list .ch-muted{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.ch-inspector{margin-top:9px;padding-top:8px;border-top:1px solid var(--dsw-alias-border-l1)}.ch-inspector>summary{display:flex;align-items:center;gap:8px;cursor:pointer;list-style:none;color:var(--dsw-alias-label-secondary);font-size:11px}.ch-inspector>summary::-webkit-details-marker{display:none}.ch-inspector>summary::after{content:'›';margin-left:auto;font-size:14px;line-height:1;transition:transform .16s ease}.ch-inspector[open]>summary::after{transform:rotate(90deg)}.ch-inspector p{margin:7px 0 0;font-size:11px;line-height:1.5}

/* Resume and work threads are secondary to the timeline, but still feel like product features. */
.ch-resume-card{padding:12px 14px;border:1px solid var(--dsw-alias-border-l1);border-radius:12px;background:var(--dsw-alias-bg-layer-1)}.ch-resume-suggestion{display:flex;align-items:center;gap:12px;padding:0}.ch-resume-suggestion .ch-app-mark{width:40px;height:40px;flex-basis:40px}.ch-resume-copy{min-width:0;flex:1}.ch-resume-open{flex:0 0 auto}.ch-resume-open-primary{box-shadow:inset 0 0 0 1px var(--dsw-alias-brand-primary);color:var(--dsw-alias-brand-primary);font-weight:650}.ch-resume-result{display:flex;align-items:center;gap:10px;margin-top:8px}.ch-resume-result>.ch-row-body{margin:0;flex:1}.ch-resume-title{display:block;font-size:14px;font-weight:650;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.ch-resume-meta{display:block;margin-top:2px;color:var(--dsw-alias-label-secondary);font-size:12px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.ch-resume-search{margin-top:10px;padding-top:9px;border-top:1px solid var(--dsw-alias-border-l1)}.ch-resume-search>summary{display:flex;align-items:center;gap:8px;cursor:pointer;list-style:none;color:var(--dsw-alias-label-secondary);font-size:12px}.ch-resume-search>summary::-webkit-details-marker{display:none}.ch-resume-search>summary::after{content:'›';margin-left:auto;font-size:15px;line-height:1;transition:transform .16s ease}.ch-resume-search[open]>summary{margin-bottom:9px}.ch-resume-search[open]>summary::after{transform:rotate(90deg)}.ch-resume-controls{display:flex;gap:8px;align-items:center}.ch-resume-controls .ch-input{flex:1}
.ch-resume-card{padding:0;border:0;border-radius:0;background:transparent}.ch-continuity-card{overflow:hidden;padding:18px 20px 16px;border:1px solid var(--dsw-alias-border-l2);border-radius:14px;background:var(--dsw-alias-bg-layer-1)}.ch-continuity-head{display:flex;align-items:center;gap:12px}.ch-continuity-actions{display:flex;align-items:center;gap:10px;flex:0 0 auto}.ch-continuity-head .ch-app-mark{width:40px;height:40px;flex-basis:40px}.ch-continue-primary{background:var(--dsw-alias-brand-primary);color:var(--dsw-alias-label-primary-inverted);box-shadow:none}.ch-continue-primary:hover:not(:disabled){background:var(--dsw-alias-button-primary-hover);box-shadow:none}.ch-open-app{white-space:nowrap}.ch-continuity-inspector{margin-top:10px}.ch-continuity-detail-label{margin:9px 0 5px;color:var(--dsw-alias-label-secondary);font-size:10px;font-weight:700;letter-spacing:.035em}.ch-continuity-files{list-style:none;margin:0;padding:0;display:grid;gap:5px}.ch-continuity-detail-files{gap:4px}.ch-continuity-files>li{display:flex;align-items:baseline;gap:10px;min-width:0;font-size:12px}.ch-continuity-file{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-weight:600}.ch-continuity-file-meta{margin-left:auto;flex:0 0 auto;color:var(--dsw-alias-label-secondary);font-size:10px}.ch-continuity-status-code{flex:0 0 22px;color:var(--dsw-alias-label-secondary);font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:10px}
.ch-thread-list{list-style:none;margin:0;padding:0;border:0;border-radius:0;background:transparent;overflow:visible}.ch-thread-item{border-top:1px solid var(--dsw-alias-border-l1)}.ch-thread-item:first-child{border-top:0}.ch-thread-action{appearance:none;display:grid;grid-template-columns:minmax(0,1fr) auto 16px;align-items:center;gap:12px;width:100%;padding:10px 0;border:0;background:transparent;color:var(--dsw-alias-label-primary);font:inherit;text-align:left;cursor:pointer}.ch-thread-action:disabled{opacity:.55;cursor:default}.ch-thread-action:hover:not(:disabled) .ch-thread-title{color:var(--dsw-alias-brand-primary)}.ch-thread-action-selected .ch-thread-title{color:var(--dsw-alias-brand-primary)}.ch-thread-leading{display:block;min-width:0}.ch-thread-copy{min-width:0}.ch-thread-title{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:13px;font-weight:650}.ch-thread-resources{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;margin-top:2px;color:var(--dsw-alias-label-secondary);font-size:11px}.ch-thread-meta{color:var(--dsw-alias-label-secondary);font-size:11px;white-space:nowrap}.ch-thread-chevron{color:var(--dsw-alias-label-secondary);font-size:17px;line-height:1;transition:transform .16s ease}.ch-thread-action-selected .ch-thread-chevron{transform:rotate(90deg)}.ch-thread-inline-status{margin:0 0 10px;padding:2px 0 4px;font-size:11px}.ch-thread-item>.ch-project-history{margin:0 0 10px}.ch-thread-more{display:flex;justify-content:center;margin-top:8px}
.ch-project-history{margin-top:10px;padding:11px 14px;border:1px solid var(--dsw-alias-border-l1);border-radius:11px;background:var(--dsw-alias-bg-layer-1)}.ch-project-history-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.ch-project-history-head .ch-muted{margin:0;font-size:11px;text-align:right}.ch-project-history-kicker{color:var(--dsw-alias-label-secondary);font-size:10px;font-weight:650;text-transform:uppercase;letter-spacing:.04em}.ch-project-days{margin-top:8px;border-top:1px solid var(--dsw-alias-border-l1)}.ch-project-day{border-bottom:1px solid var(--dsw-alias-border-l1)}.ch-project-day:last-child{border-bottom:0}.ch-project-day-head{display:grid;grid-template-columns:minmax(0,1fr) auto 14px;align-items:center;gap:10px;padding:9px 0;list-style:none;cursor:pointer;color:var(--dsw-alias-label-secondary);font-size:11px}.ch-project-day-head::-webkit-details-marker{display:none}.ch-project-day-chevron{font-size:15px;line-height:1;transition:transform .16s ease}.ch-project-day[open] .ch-project-day-chevron{transform:rotate(90deg)}.ch-project-activity-list{list-style:none;margin:0;padding:0 0 5px}.ch-project-activity-list>li{display:grid;grid-template-columns:80px 28px minmax(0,1fr) auto;align-items:center;gap:10px;min-height:48px;border-top:1px solid var(--dsw-alias-border-l1)}.ch-project-time,.ch-project-duration{color:var(--dsw-alias-label-secondary);font-size:10px;font-variant-numeric:tabular-nums}.ch-project-activity-copy{min-width:0}.ch-project-activity-title{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:11px;font-weight:600}.ch-project-activity-meta{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;margin-top:1px;color:var(--dsw-alias-label-secondary);font-size:10px}
.ch-summary-disclosure{margin-top:8px;border-top:1px solid var(--dsw-alias-border-l1);padding-top:12px}.ch-summary-disclosure>summary{display:flex;align-items:center;gap:8px;cursor:pointer;list-style:none;color:var(--dsw-alias-label-secondary);font-size:12px}.ch-summary-disclosure>summary::-webkit-details-marker{display:none}.ch-summary-status{margin-left:auto}.ch-summary-chevron{font-size:16px;line-height:1;transition:transform .16s ease}.ch-summary-disclosure[open] .ch-summary-chevron{transform:rotate(90deg)}.ch-summary-body{padding-top:10px}.ch-summary-list{list-style:none;margin:8px 0 0;padding:0}.ch-summary-item{padding:8px 0;border-top:1px solid var(--dsw-alias-border-l1)}.ch-summary-item:first-child{border-top:0}.ch-summary-item-title{font-size:12px;font-weight:600}.ch-controls{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin-top:8px}

/* Settings: overview first, technical controls only after disclosure. */
.ch-settings-list{list-style:none;margin:0;padding:0;border:0;border-radius:0;background:transparent;overflow:visible}.ch-settings-item{border-top:1px solid var(--dsw-alias-border-l1)}.ch-settings-item:first-child{border-top:0}.ch-settings-line,.ch-settings-summary{display:grid;grid-template-columns:40px minmax(0,1fr) auto;align-items:center;gap:13px;min-height:70px;padding:10px 0}.ch-settings-summary{cursor:pointer;list-style:none}.ch-settings-summary::-webkit-details-marker{display:none}.ch-settings-icon-wrap{display:grid;place-items:center;box-sizing:border-box;width:36px;height:36px;border-radius:10px;background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-secondary)}.ch-settings-icon{display:block;width:20px;height:20px}.ch-settings-skeleton-icon{display:block;width:36px;height:36px;border-radius:10px;background:var(--dsw-alias-border-l2)}.ch-settings-copy{min-width:0}.ch-settings-title{display:block;font-size:13px;font-weight:650}.ch-settings-description{display:block;margin-top:2px;color:var(--dsw-alias-label-secondary);font-size:12px;line-height:1.45}.ch-settings-value{display:flex;align-items:center;gap:7px;color:var(--dsw-alias-label-secondary);font-size:12px;white-space:nowrap}.ch-chevron{font-size:17px;line-height:1;color:var(--dsw-alias-label-secondary)}
.ch-settings-detail{padding:0 0 16px 53px}.ch-settings-detail>.ch-row-body{margin:0 0 10px}.ch-row-body{margin:4px 0 0;font-size:12px;line-height:1.55;color:var(--dsw-alias-label-secondary)}.ch-row-title{margin:0;font-size:13px;font-weight:600}.ch-list{list-style:none;margin:0 0 7px;padding:0;border:1px solid var(--dsw-alias-border-l1);border-radius:10px}.ch-list-more{display:block;margin:0 0 10px}.ch-list>li{display:flex;align-items:center;gap:8px;padding:7px 9px;border-top:1px solid var(--dsw-alias-border-l1)}.ch-list>li:first-child{border-top:0}.ch-list>li>.ch-row-body{margin:0;min-width:0;flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px}.ch-app-rule-copy{min-width:0;flex:1}.ch-app-rule-title{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:12px;font-weight:600}.ch-app-rule-id{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;margin-top:1px;color:var(--dsw-alias-label-secondary);font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:10px}.ch-list .ch-button{height:26px;padding:0 8px;border-radius:8px;font-size:11px}.ch-list .ch-button-danger{box-shadow:none;background:transparent;color:var(--dsw-alias-label-secondary)}.ch-list .ch-button-danger:hover:not(:disabled),.ch-list .ch-button-danger:focus-visible{box-shadow:none;color:var(--dsw-alias-state-error-primary);text-decoration:underline}.ch-manual-add{margin-top:8px}.ch-manual-add>summary{cursor:pointer;list-style:none;color:var(--dsw-alias-label-secondary);font-size:12px}.ch-manual-add>summary::-webkit-details-marker{display:none}.ch-manual-add>summary::before{content:'＋';display:inline-block;margin-right:5px;color:var(--dsw-alias-label-secondary)}.ch-manual-add[open]>summary{margin-bottom:8px}
.ch-input{box-sizing:border-box;height:34px;min-width:0;padding:0 10px;border:1px solid var(--dsw-alias-border-l1);border-radius:9px;background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary);font:inherit;font-size:13px}.ch-input-small{width:96px}.ch-field-label{display:flex;align-items:center;gap:7px;font-size:12px;color:var(--dsw-alias-label-secondary)}
.ch-switch{position:relative;width:40px;height:24px;border:0;border-radius:999px;background:var(--dsw-alias-bg-layer-2);box-shadow:inset 0 0 0 1px var(--dsw-alias-border-l1);cursor:pointer}.ch-switch::after{content:"";position:absolute;top:3px;left:3px;width:18px;height:18px;border-radius:999px;background:var(--dsw-alias-label-secondary);transition:transform .16s ease,background .16s ease}.ch-switch[aria-checked="true"]{background:var(--dsw-alias-brand-primary);box-shadow:none}.ch-switch[aria-checked="true"]::after{transform:translateX(16px);background:var(--dsw-alias-bg-base)}.ch-switch:disabled{opacity:.5;cursor:default}
.ch-settings-status-dot{width:7px;height:7px;border-radius:999px;background:var(--dsw-alias-state-idle-primary)}.ch-settings-status-dot-success{background:var(--dsw-alias-state-success-primary)}.ch-settings-status-dot-warn{background:var(--dsw-alias-state-warn-primary)}.ch-settings-danger .ch-settings-title{color:var(--dsw-alias-state-error-primary)}
.ch-settings-danger .ch-settings-icon-wrap{color:var(--dsw-alias-state-error-primary)}.ch-delete-ranges{display:flex;flex-wrap:wrap;gap:7px;margin-top:9px}.ch-range-button{height:32px;font-size:12px}.ch-range-button-selected{box-shadow:inset 0 0 0 1px var(--dsw-alias-brand-primary);color:var(--dsw-alias-brand-primary)}.ch-delete-confirm{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin-top:10px;padding-top:10px;border-top:1px solid var(--dsw-alias-border-l1)}.ch-delete-confirm>.ch-row-body{margin:0 auto 0 0}.ch-browser-setup{margin-top:13px;border-top:1px solid var(--dsw-alias-border-l1)}.ch-setup-step{padding:13px 0;border-top:1px solid var(--dsw-alias-border-l1)}.ch-setup-step:first-child{border-top:0}.ch-setup-step h4{margin:0;font-size:13px;font-weight:650}.ch-setup-step h4+.ch-row-body{margin-top:4px}.ch-extension-path{display:grid;gap:5px;margin-top:10px;padding:9px 10px;border-radius:9px;background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-secondary);font-size:11px}.ch-extension-path code{overflow-wrap:anywhere;color:var(--dsw-alias-label-primary);font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px}.ch-setup-privacy{margin:8px 0 0;color:var(--dsw-alias-label-secondary);font-size:11px;line-height:1.45}.ch-setup-status{display:grid;grid-template-columns:auto minmax(0,1fr);align-items:center;gap:6px;margin-top:9px;color:var(--dsw-alias-label-secondary);font-size:11px}.ch-setup-status-age{grid-column:2}.ch-token-block{margin-top:9px}.ch-token-block .ch-code{white-space:pre-wrap;overflow-wrap:anywhere}

@media(max-width:720px){.ch-main{padding:22px 18px 34px}.ch-first-run{margin-top:24px;padding:20px}.ch-first-run-action{align-items:flex-start;flex-direction:column}.ch-status-line{flex-wrap:wrap;white-space:normal}.ch-state-card{grid-template-columns:40px minmax(0,1fr)}.ch-state-card>.ch-button{grid-column:2;width:max-content}.ch-skeleton-row{grid-template-columns:72px minmax(0,1fr)}.ch-skeleton-row>.ch-skeleton-tiny{display:none}.ch-timeline-item{grid-template-columns:76px minmax(0,1fr)}.ch-timeline-item::after{left:108px}.ch-duration-wrap{grid-column:2;justify-items:start;margin-top:-6px;padding-bottom:8px}.ch-duration-track{width:68px}.ch-timeline-detail{grid-column:2;margin-top:-3px}.ch-thread-item{grid-template-columns:1fr}.ch-thread-meta{white-space:normal}.ch-settings-detail{padding-left:0}.ch-settings-line,.ch-settings-summary{grid-template-columns:36px minmax(0,1fr) auto;gap:10px;padding-left:0;padding-right:0}.ch-settings-icon-wrap,.ch-settings-skeleton-icon{width:32px;height:32px}.ch-settings-icon{width:18px;height:18px}}
@media(max-width:720px){.ch-continuity-head{align-items:flex-start;flex-wrap:wrap}.ch-continuity-head .ch-resume-copy{flex:1 1 220px}.ch-continuity-actions{margin-left:52px;align-items:flex-start;flex-direction:column}.ch-open-app{white-space:normal}}
@media(max-width:560px){.ch-resume-controls{align-items:stretch;flex-direction:column}.ch-resume-controls .ch-input,.ch-resume-controls .ch-button{width:100%}}
`

let stylesInstalled = false

export function installHistoryStyles(): () => void {
  if (stylesInstalled || typeof document === 'undefined') return () => {}
  stylesInstalled = true
  const tag = document.createElement('style')
  tag.dataset.plugin = 'dsh-computer-history'
  tag.textContent = CSS
  document.head.appendChild(tag)
  return () => {
    tag.remove()
    stylesInstalled = false
  }
}
