import { describe, expect, it } from 'vitest'
import {
  captureLabel,
  en,
  episodeLineText,
  failureText,
  reasonText,
  threadSubjectText,
  zh,
  type HistoryTranslate,
} from '../../src/client/locale.js'

function placeholders(value: string): string[] {
  return [...value.matchAll(/\{([^}]+)\}/g)]
    .map(match => match[1]!)
    .toSorted()
}

describe('client locale contract', () => {
  it('keeps English and Chinese templates structurally compatible', () => {
    expect(Object.keys(zh).toSorted()).toEqual(Object.keys(en).toSorted())
    for (const key of Object.keys(en) as (keyof typeof en)[]) {
      expect(placeholders(zh[key]), key).toEqual(placeholders(en[key]))
    }
  })

  it('maps capture protocol words through the locale namespace', () => {
    const t = ((key: keyof typeof en) => en[key]) as HistoryTranslate
    expect(captureLabel(t, 'running')).toBe('recording')
    expect(captureLabel(t, 'permission-required')).toBe('needs permission')
    expect(captureLabel(t, 'future-state')).toBe('future-state')
  })
})

// A browser network failure is not UI copy: `fetch` rejects with `TypeError: Failed to fetch`, and printing
// that message is what the rendered panel used to do. The mapping lives in the owned locale layer and is
// asserted in both languages, with an unknown cause still surfacing its own text.
describe('failureText', () => {
  const en_t = ((key: keyof typeof en) => en[key]) as HistoryTranslate
  const zh_t = ((key: keyof typeof zh) => zh[key]) as HistoryTranslate

  it('turns a browser network failure into a sentence in the interface language', () => {
    const failure = new TypeError('Failed to fetch')
    expect(failureText(zh_t, failure)).toBe('无法连接到宿主。')
    expect(failureText(en_t, failure)).toBe('Could not reach the Host.')
  })

  it('keeps an unknown cause truthful instead of replacing it', () => {
    const other = new Error('capture is owned by another DSH Host')
    expect(failureText(zh_t, other)).toBe('capture is owned by another DSH Host')
  })
})

// Stored summaries are English prose generated by the Host and were printed straight into the panel. The
// views now compose their lines from structured fields, and these assert the composition, including the
// fallbacks, in both languages.
// The bound translator substitutes `{name}` placeholders; the raw dictionary does not.
function translator(dict: Record<string, string>): HistoryTranslate {
  return ((key: string, params?: Record<string, string | number>) =>
    String(dict[key]).replace(/\{(\w+)\}/g, (_match, name: string) => String(params?.[name] ?? ''))) as HistoryTranslate
}

describe('host data rendered in the reader\'s language', () => {
  const en_t = translator(en)
  const zh_t = translator(zh)
  const resource = { displayLabel: 'notes.md', canonicalUri: 'file:///notes.md' }

  it('names a known Host reason in the interface language and keeps an unknown one', () => {
    expect(reasonText(zh_t, 'capture-owned-by-another-host'))
      .toBe('这台机器上已有另一个 DSH 宿主在采集，这里不会重复记录。')
    expect(reasonText(en_t, 'capture-owned-by-another-host'))
      .toBe('Another DSH Host is already recording on this machine.')
    expect(reasonText(en_t, 'something-new-from-a-later-host')).toBe('something-new-from-a-later-host')
  })

  it('composes a timeline row from the evidence it carries', () => {
    expect(episodeLineText(en_t, { resources: [resource], surfaces: [{ bundleId: 'com.apple.Notes' }] }))
      .toBe('Files: notes.md · Apps: com.apple.Notes')
    expect(episodeLineText(zh_t, { resources: [resource], surfaces: [{ bundleId: 'com.apple.Notes' }] }))
      .toBe('文件：notes.md · 应用：com.apple.Notes')
    expect(episodeLineText(zh_t, { resources: [], surfaces: [] })).toBe('没有可见的文件或应用')
  })

  it('names the workspace when the Host carried it, and says so when it did not', () => {
    expect(threadSubjectText(zh_t, { workspaceTitle: 'dsh-computer-history', resources: [resource] }))
      .toBe('dsh-computer-history · notes.md')
    expect(threadSubjectText(en_t, { resources: [] })).toBe('an unnamed workspace')
  })
})
